# Generated by Django 4.2.5 on 2023-10-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_problem_assigned_user_problem_resolved_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('resolved', 'Решена'), ('confirmed', 'Подтверждена')], default='new', max_length=15),
        ),
    ]
